// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwraztvcsorpevxfiqal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3cmF6dHZjc29ycGV2eGZpcWFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNDA0MTcsImV4cCI6MjA1ODYxNjQxN30.VQ8g3dMOPpvyGsi1nZMF9iy6Z9mYZqKHHy7inwWrPMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);